[build]
  command = "npm install && npx prisma generate && npx prisma migrate deploy"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/server.js"
  status = 200
